name: CI Check

on:
  push:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build
      run: ./gradlew assembleFreeDebug
    - name: Spotless Check
      run: ./gradlew spotlessCheck
    - name: Run tests
      run: ./gradlew testFreeDebug
