name: CI Check

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
    - name: Build
      run: ./gradlew assembleFreeDebug
    - name: Spotless Check
      run: ./gradlew spotlessCheck
    - name: Run tests
      run: ./gradlew testFreeDebug
